### ISSUE TITLE
Request for instructions - not running in 64 bit Win 7

### ISSUE THREAD

**Issue by ghost** [Shoop123/Reworder-C-Sharp#1]
Hi:

Your program looks very interesting and I would like to test it on a win 7 64 bit machine. Unfortunately, I get the following errors when trying to run any .exe file before startup:

Files that help describe the problem:
  C:\Users\PIXELHEAD\AppData\Local\Temp\WERF110.tmp.WERInternalMetadata.xml
  C:\Users\PIXELHEAD\AppData\Local\Temp\WER77E.tmp.appcompat.txt
  C:\Users\PIXELHEAD\AppData\Local\Temp\WER9C0.tmp.mdmp

I've saved the above files. Do you have instructions that you can post for running the existing .exes and compiling the project for 64 bit win 7 ? 

Also, could you provide brief explanations on the features of your program?

Thanks,

**Comment by Shoop123** [comment]
Sorry for your trouble, but I actually never encountered that error before.
As I'm sure you've Googled it already, I cant really say anything other
than the fact that I developed it on a 64 bit Windows 7 machine. So I don't
think i can help you with that... Sorry.

A suggestion I can give you is try building it in visual studio, and
running it like that. FYI you might run into directory issues because many
directories are hardcoded, so if you find a string that specifies a
specific location, you'll need to change it to the respective directory on
your local machine.

As for the features, if they're still of any use to you, all it does is
poorly attempt to reword whatever sentence you give it it has some grammar
check options as well. This project was abandoned by me and my friend so
that we can work on something a little more useful and challenging - a
simplifier. Unfortunately though we cant give you that code because its a
little private, but if you're interested you can check it out over here:
http://162.243.1.107

**Comment by ghost** [comment]
Thanks for the quick reply. I''ll try on another win 7 machine and
recompiling.

Your simplifier code looks promising.

Good luck
